import type { Metadata } from "next";
import { Orbitron, DM_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ThemeScript } from "@/components/providers/theme-script";
import { themeConfig } from "@/lib/theme";

// Primary — display / headings
const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

// Secondary — body / UI text
const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      /* the theme script writes the class on <html> before hydration */
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        orbitron.variable,
        dmSans.variable,
        geistMono.variable,
        "font-sans",
      )}
    >
      <head>
        {/*
          Server rendered on purpose: a <script> produced while rendering on
          the client never runs, and React logs "Encountered a script tag while
          rendering React component". This one applies the stored theme before
          the first paint, which a client provider could never guarantee.
        */}
        <ThemeScript {...themeConfig} />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider {...themeConfig} disableTransitionOnChange>
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster richColors position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
